### ISSUE TITLE
Support node 0.8.x

### ISSUE THREAD

**Issue by temsa** [theturtle32/WebSocket-Node#48]
Validation seems not to work with 1.0.6 package (used by socket.io) after upgrade to node 0.8.0

```
websocket/lib/Validation.js:17
  throw e;
        ^
Error: Cannot find module '../build/default/validation'

```

Troubleshoot :  doing a `npm install websockets@1.0.3` seems to fix the problem ( as there is no native module used )
