### ISSUE TITLE
Doesn't work with Node 0.12.7 on Windows 7

### ISSUE THREAD

**Issue by polkovnikov-ph** [theturtle32/WebSocket-Node#211]
bufferutil.cc
	..\src\bufferutil.cc(8): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory [D:\heroku\im\node_modules\websocket\build\bufferutil.	vcxproj]
	  validation.cc
	..\src\validation.cc(8): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory [D:\heroku\im\node_modules\websocket\build\validation.vcxproj]

**Comment by theturtle32** [comment]
Is this still an outstanding issue?

**Comment by theturtle32** [comment]
Please re-open if so.
